services:
  app:
    container_name: hyperf-example-app
    image: hyperf-example-app
    build:
      context: .
      args:
        - APP_ENV=dev
    command: [ "server:watch" ]
    volumes:
      - ./:/opt/www
    ports:
      - "9501:9501"
    environment:
      - SCAN_CACHEABLE=false
      - STDOUT_LOG_LEVEL=alert,critical,emergency,error,warning,notice,info
    networks:
      - hyperf-example-network
    restart: on-failure

networks:
  hyperf-example-network:
    name: hyperf-example-network
